### ISSUE TITLE
la variable $container queda como global

### ISSUE THREAD

**Issue by nkvenom** [prigazzi/slider-jquery#1]
no es gran cosa, pero no se si pueda dar problemas al usar dos sliders al mismo tiempo, Por cierto, muy buen ejemplo, muchos de los otros sliders que hay por ahi se devuelven de forma poco graciosa cuando llegan al final

**Comment by prigazzi** [comment]
Muchísimas gracias por dejar un comentario. Te juro que ya dudaba que alguien usara Github como corresponde, porque en varios proyectos no conseguía ni un fork, ni un comentario, mucho menos un pull-request. Has venido hoy a devolverme la fe en la humanidad :)

Dejame revisar el código, voy a colocar dos Sliders y te digo.

**Comment by prigazzi** [comment]
Listo, corregido ya, y listo para utilizar distintos sliders. Gracias por reportar esto :)
